const projects = [
  {
    title: "Dynamic 5S",
    role: "Team Leader & AI Engineer",
    description: "Dynamic 5S is a computer vision app built in a month-long AI bootcamp by a team of four to detect 5S compliance on computer lab desks. Trained on 1,000+ custom-labeled images, our YOLO model achieved over 90% accuracy, automating audits and showcasing scalable, real-world innovation.",
    image: "/assets/project/dynamic5s.png",
    tech: ["python", "flask", "roboflow", "ultralytics"],
    github: "https://github.com/haemuucia/dynamic5s",
    demo: "",
    category: ["AI", "Web Development"],
  },
  {
    title: "Personal Portfolio",
    role: "Web Developer",
    description: "A fully responsive personal portfolio website designed to showcase my projects, skills, and achievements. Built with a modern tech stack, it highlights my expertise in AI, web, and mobile development through interactive UI, smooth navigation, and project-based storytelling.",
    image: "/assets/project/portfolio.png",
    tech: ["nextjs", "tailwind", "typescript"],
    github: "https://github.com/haemuucia/dynamic5s",
    demo: "",
    category: ["Web Development"],
  },
  {
    title: "SI-WAQU (Water Quality Controller)",
    role: "AI Engineer, Web Designer, Web Developer",
    description: "SI-WAQU is a smart water quality controller built using four environmental sensors and trained on 2000+ data entries. It classifies water into 5 quality levels, identifies possible causes of poor conditions such as high TDS or low pH, and provides targeted solutions to improve water quality. This system enables real-time monitoring and supports smarter water management.",
    image: "/assets/project/sic.png",
    tech: ["arduino", "python", "streamlit", "mongodb"],
    github: "https://github.com/haemuucia/finalproject",
    demo: "",
    category: ["AI", "Web Development"],
  },
  {
    title: "Image Caption Generator",
    role: "Frontend Developer & AI Engineer",
    description: "Built in just one week for a Distributed & Parallel Systems course, this web app auto-generates captions for user-uploaded images in 5+ tones and translates them into 10+ languages, offering a seamless multilingual image-to-text experience",
    image: "/assets/project/imagecaption.jpeg",
    tech: ["docker", "python", "flask", "tailwind"],
    github: "https://github.com/RevokatusIvo/DPS-Project",
    demo: "",
    category: ["AI", "Web Development"],
  },
  {
    title: "Image Processing and Editing",
    role: "Team Leader & AI Engineer",
    description: "Built in one week for an Image Processing and Recognition course, this project was developed by a team of 4 and offers 10+ key features, including image enhancement, transformation, filtering, and edge detection.",
    image: "/assets/project/imp.jpeg",
    tech: ["python", "php", "flask"],
    github: "https://github.com/haemuucia/final-project_imp",
    demo: "",
    category: ["AI", "Web Development"],
  },
  {
    title: "Lecturer Appointment",
    role: "Team Leader & App Developer",
    description: "A native Android app enabling students to book and manage appointments with 10+ lecturers via a role-based interface. Includes 3+ core features, achieving booking completion in <20s and supporting instant data filtering.",
    image: "/assets/project/lecturerappointment.png",
    tech: ["java", "android studio", "firebase"],
    github: "https://github.com/bilaaur/lecturerappointment",
    demo: "",
    category: ["Mobile Development"],
  },
  {
    title: "Pet Shop",
    role: "Web Development",
    description: "ava-based desktop app with 5 core modules. Built using NetBeans and Swing with 12+ interactive GUI components like JTable and JComboBox, enabling smooth in-app navigation and full CRUD access for employees.",
    image: "/assets/project/petshopp.jpeg",
    tech: ["java", "mysql"],
    github: "",
    demo: "",
    category: ["Web Development"],
  },
  {
    title: "Emotion Detection",
    role: "Team Leader & AI Engineer",
    description: "One-week computer vision project built by a team of 4 to detect 7 facial emotions. Trained on 1,000+ labeled images to classify expressions with real-time prediction capability.",
    image: "/assets/project/cv.jpeg",
    tech: ["python"],
    github: "https://github.com/haemuucia/emotionrecognition",
    demo: "",
    category: ["AI"],
  },
  {
    title: "Question Answering Chatbot for Medical Questions",
    role: "Team Leader & AI Engineer",
    description: "A medical chatbot trained on 1,000+ QA samples, using dual-model architecture for accurate answer generation and context understanding. Supports dynamic memory to fetch and respond with the latest conversation flow.",
    image: "/assets/project/nlug.jpeg",
    tech: ["python", "streamlit"],
    github: "",
    demo: "",
    category: ["AI", "Web Development"],
  },
  {
    title: "Voice to Text Generator",
    role: "Team Leader & AI Engineer",
    description: "A one-week NLP project that converts up to 1-minute recorded speech into accurate text, designed for the Natural Language Understanding course to demonstrate real-time audio transcription capabilities",
    image: "/assets/project/nlp.jpeg",
    tech: ["python"],
    github: "",
    demo: "",
    category: ["AI"],
  },
  {
    title: "NUTRICAL (Food Calorie Counter & Meal Planner)",
    role: "Web Designer",
    description: "Nutrical is a smart nutrition assistant that helps users track and manage their diet through AI-powered features. It calculates daily macronutrient needs based on TDEE, analyzes food from images to estimate nutritional content, and generates personalized meal plans tailored to individual goals.",
    image: "/assets/project/nlp.jpeg",
    tech: ["figma", "flutter"],
    github: "https://github.com/RasonYudha4/nutrical/",
    demo: "",
    category: ["AI", "Mobile Development"],
  },
];

export default projects;